import type { KioCase } from "./types";
import { withDerivedCaseFields } from "./domain/caseStateSelectors";
import type {
  AiProcessingJob,
  BiomarkerOutput,
  ImageQualityAssessment,
  MriStudyReference,
  PatientSafeSummaryDraft,
  PatientReleasePackage,
  PatientReleaseSafetyCheck,
  PhysicianClinicalSynthesis,
  PhysicianEvidenceReview,
  ProtocolCompletenessAssessment,
  PublicationApproval,
  QuantitativeReportPlaceholder,
  RadiologistImagingHandoff,
  SegmentationQc,
  StructuredReport,
  StructuredVisualAssessment,
} from "./domain";

const rawInitialCases: KioCase[] = [
  {
    id: "K-2041",
    state: "RADIOLOGIST_REVIEW_COMPLETED",
    mriStudyIds: ["mri-K-2041-T0"],
    aiProcessingJobIds: ["aijob-K-2041-01"],
    biomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    quantitativeReportIds: ["qreport-K-2041-rad-summary-01"],
    protocolCompletenessAssessmentIds: ["proto-K-2041-01"],
    imageQualityAssessmentIds: ["imgqc-K-2041-01"],
    structuredVisualAssessmentIds: ["sva-K-2041-01"],
    radiologistHandoffIds: ["handoff-K-2041-01"],
    structuredReportIds: ["sreport-K-2041-rad-quant-01", "sreport-K-2041-rad-visual-01", "sreport-K-2041-phys-evidence-01", "sreport-K-2041-patient-safe-draft-01"],
    physicianSynthesisIds: ["phys-synth-K-2041-01"],
    physicianEvidenceReviewIds: ["phys-evrev-K-2041-01"],
    patientSafeSummaryDraftIds: ["ps-summary-K-2041-01"],
    anonymizedId: "R-1184",
    patientName: "Leila Rahimi",
    age: 67,
    ageGroup: "65–69",
    sex: "Female",
    scanDate: "2026-06-11",
    caseStatus: "Ready for physician review",
    mriStatus: "Received",
    intakeStatus: "Complete",
    aiStatus: "AI output ready",
    radiologistStatus: "Radiologist reviewed",
    neurologistStatus: "Review pending",
    reportStatus: "Draft",
    patientSummaryStatus: "Not prepared",
    pdfReleaseStatus: "Not approved",
    releaseStatus: "Not released",
    followUpStatus: "Not scheduled",
    nextAction: "Physician clinical review",
    currentOwnerRole: "Neurologist / Physician",
    assignedRadiologist: "Dr. N. Azadi",
    assignedNeurologist: "Dr. P. Sadeghi",
    imageQuality: "Acceptable",
    memoryComplaint: "Gradual short-term memory concerns reported over 14 months.",
    cognitiveHistory: "Independent daily activity with increasing reliance on written reminders.",
    cognitiveScore: "MoCA 23 / 30",
    caregiverObservation: "Occasional repetition and missed appointments.",
    keyFindings: ["Hippocampal volume below reference range", "Mild ventricular enlargement indication"],
    findings: [
      { region: "Left hippocampus", volume: "2.41 cm³", percentile: 4, comparison: "Below reference", indication: "Atrophy indication" },
      { region: "Right hippocampus", volume: "2.58 cm³", percentile: 8, comparison: "Lower reference range" },
      { region: "Lateral ventricles", volume: "37.2 cm³", percentile: 91, comparison: "Upper reference range", indication: "Enlargement indication" },
      { region: "Whole brain", volume: "1,041 cm³", percentile: 36, comparison: "Within reference" },
    ],
    timeline: [
      { label: "Case created", detail: "Referral received from memory clinic", date: "Jun 09", patientSafe: true },
      { label: "MRI received", detail: "Study matched and quality checked", date: "Jun 11", tone: "good", patientSafe: true },
      { label: "AI output ready", detail: "Quantitative draft generated", date: "Jun 11" },
      { label: "Radiologist reviewed", detail: "Reviewed with limitations noted", date: "Jun 12", tone: "good" },
      { label: "Physician review pending", detail: "Clinical context is complete", date: "Today", patientSafe: true },
    ],
    outputVersion: "AI-v1.2 · output 03",
    reportVersion: "Report draft v0.3",
    amendmentStatus: "No amendment",
    researchEligible: true,
    researchConsent: "Consented",
    consentScope: "MRI-derived metrics and de-identified clinical labels",
    anonymizationStatus: "Anonymized",
    anonymizationMethod: "Age band + relative timepoint",
    researchTimepoint: "Baseline · T0",
    datasetVersion: "Dataset v0.4",
    exportVersion: "No export",
    withdrawalStatus: "No withdrawal",
    longitudinal: false,
    patientSafeStatus: "Report under physician review",
    patientNextAction: "No action is needed from you right now.",
    patientFormProgress: 100,
    consentStatus: "Complete",
    radiologistComment: "Image quality acceptable. Quantitative findings may be interpreted in clinical context.",
    physicianNote: "",
  },
  {
    id: "K-2042",
    state: "RADIOLOGIST_REVIEW_IN_PROGRESS",
    mriStudyIds: ["mri-K-2042-T0"],
    aiProcessingJobIds: ["aijob-K-2042-01"],
    biomarkerOutputIds: ["bio-K-2042-vol-01"],
    quantitativeReportIds: ["qreport-K-2042-tech-01"],
    protocolCompletenessAssessmentIds: ["proto-K-2042-01"],
    imageQualityAssessmentIds: ["imgqc-K-2042-01"],
    structuredVisualAssessmentIds: ["sva-K-2042-01"],
    structuredReportIds: ["sreport-K-2042-rad-quant-draft-01"],
    anonymizedId: "R-1191",
    patientName: "Amir Hosseini",
    age: 72,
    ageGroup: "70–74",
    sex: "Male",
    scanDate: "2026-06-13",
    caseStatus: "Radiologist review pending",
    mriStatus: "Received",
    intakeStatus: "Complete",
    aiStatus: "AI output ready",
    radiologistStatus: "Review pending",
    neurologistStatus: "Not ready",
    reportStatus: "AI-generated draft",
    patientSummaryStatus: "Not prepared",
    pdfReleaseStatus: "Not approved",
    releaseStatus: "Not released",
    followUpStatus: "Not scheduled",
    nextAction: "Radiologist imaging review",
    currentOwnerRole: "Radiologist",
    assignedRadiologist: "Dr. N. Azadi",
    assignedNeurologist: "Dr. P. Sadeghi",
    imageQuality: "Acceptable",
    memoryComplaint: "Recent difficulty recalling names and conversations.",
    cognitiveHistory: "Symptoms reported as slowly increasing over 10 months.",
    cognitiveScore: "MoCA 21 / 30",
    caregiverObservation: "Needs reminders for complex tasks.",
    keyFindings: ["Temporal lobe volume lower reference range", "No processing warning"],
    findings: [
      { region: "Left hippocampus", volume: "2.63 cm³", percentile: 12, comparison: "Lower reference range" },
      { region: "Right hippocampus", volume: "2.71 cm³", percentile: 15, comparison: "Lower reference range" },
      { region: "Temporal lobe", volume: "101.8 cm³", percentile: 9, comparison: "Lower reference range" },
      { region: "Whole brain", volume: "1,028 cm³", percentile: 30, comparison: "Within reference" },
    ],
    timeline: [
      { label: "Case created", detail: "Clinic-created case", date: "Jun 12", patientSafe: true },
      { label: "Intake completed", detail: "Patient and caregiver forms received", date: "Jun 12", patientSafe: true },
      { label: "MRI received", detail: "PACS study matched", date: "Jun 13", tone: "good", patientSafe: true },
      { label: "AI output ready", detail: "Pending specialist review", date: "Today" },
    ],
    outputVersion: "AI-v1.2 · output 01",
    reportVersion: "Report draft v0.1",
    amendmentStatus: "No amendment",
    researchEligible: true,
    researchConsent: "Consented",
    consentScope: "MRI-derived metrics only",
    anonymizationStatus: "Anonymized",
    anonymizationMethod: "Age band + relative timepoint",
    researchTimepoint: "Baseline · T0",
    datasetVersion: "Dataset v0.4",
    exportVersion: "No export",
    withdrawalStatus: "No withdrawal",
    longitudinal: false,
    patientSafeStatus: "Your case is under specialist review",
    patientNextAction: "No action is needed from you right now.",
    patientFormProgress: 100,
    consentStatus: "Complete",
    radiologistComment: "",
    physicianNote: "",
  },
  {
    id: "K-2043",
    state: "FOLLOW_UP_COORDINATION_PENDING",
    mriStudyIds: ["mri-K-2043-T0", "mri-K-2043-T1"],
    aiProcessingJobIds: ["aijob-K-2043-long-01"],
    biomarkerOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    quantitativeReportIds: ["qreport-K-2043-phys-evidence-01"],
    protocolCompletenessAssessmentIds: ["proto-K-2043-01"],
    imageQualityAssessmentIds: ["imgqc-K-2043-01"],
    structuredVisualAssessmentIds: ["sva-K-2043-01"],
    radiologistHandoffIds: ["handoff-K-2043-01"],
    structuredReportIds: ["sreport-K-2043-phys-evidence-01", "sreport-K-2043-patient-safe-draft-01"],
    physicianSynthesisIds: ["phys-synth-K-2043-01"],
    physicianEvidenceReviewIds: ["phys-evrev-K-2043-01"],
    patientSafeSummaryDraftIds: ["ps-summary-K-2043-01"],
    anonymizedId: "R-1204",
    patientName: "Mina Karimi",
    age: 64,
    ageGroup: "60–64",
    sex: "Female",
    scanDate: "2026-05-24",
    caseStatus: "Patient output released",
    mriStatus: "Received",
    intakeStatus: "Complete",
    aiStatus: "AI output ready",
    radiologistStatus: "Radiologist reviewed",
    neurologistStatus: "Physician reviewed",
    reportStatus: "Released",
    patientSummaryStatus: "Approved",
    pdfReleaseStatus: "Released",
    releaseStatus: "Patient output released",
    followUpStatus: "Scheduled · Dec 2026",
    nextAction: "Coordinate follow-up",
    currentOwnerRole: "Operations",
    assignedRadiologist: "Dr. M. Farzan",
    assignedNeurologist: "Dr. L. Vaziri",
    imageQuality: "Acceptable",
    memoryComplaint: "Follow-up review for previously documented memory concerns.",
    cognitiveHistory: "Stable daily function since baseline review.",
    cognitiveScore: "MoCA 25 / 30",
    caregiverObservation: "No material functional change reported.",
    keyFindings: ["Longitudinal pair available", "Comparison reviewed with no quality limitation"],
    findings: [
      { region: "Left hippocampus", volume: "2.76 cm³", percentile: 18, comparison: "Stable from baseline" },
      { region: "Right hippocampus", volume: "2.82 cm³", percentile: 20, comparison: "Stable from baseline" },
      { region: "Lateral ventricles", volume: "31.9 cm³", percentile: 76, comparison: "Comparable to baseline" },
      { region: "Whole brain", volume: "1,076 cm³", percentile: 45, comparison: "Within reference" },
    ],
    timeline: [
      { label: "Case opened", detail: "Follow-up review", date: "May 22", patientSafe: true },
      { label: "MRI received", detail: "Follow-up study received", date: "May 24", patientSafe: true },
      { label: "Specialist review completed", detail: "Clinical review completed", date: "May 27", tone: "good", patientSafe: true },
      { label: "Report available", detail: "Physician-approved summary released", date: "May 28", tone: "good", patientSafe: true },
      { label: "Follow-up scheduled", detail: "Next review point in December", date: "May 28", patientSafe: true },
    ],
    outputVersion: "AI-v1.2 · output 05",
    reportVersion: "Final report v1.0",
    amendmentStatus: "No amendment",
    researchEligible: true,
    researchConsent: "Consented",
    consentScope: "MRI-derived metrics and approved follow-up labels",
    anonymizationStatus: "Anonymized",
    anonymizationMethod: "Age band + relative interval",
    researchTimepoint: "Follow-up · T1 · 12-month interval",
    datasetVersion: "Dataset v0.4",
    exportVersion: "Export draft v0.1",
    withdrawalStatus: "No withdrawal",
    longitudinal: true,
    patientSafeStatus: "Report available",
    patientNextAction: "Your follow-up review is scheduled for December 2026.",
    patientApprovedSummary: "Your specialist-reviewed summary is available. Please review it with your clinic or specialist team if you have questions about your care.",
    patientFormProgress: 100,
    consentStatus: "Complete",
    radiologistComment: "Baseline and follow-up studies are comparable.",
    physicianNote: "Reviewed in clinical context. Continue existing care discussion outside Kio.",
  },
  {
    id: "K-2044",
    state: "IMAGE_QUALITY_FAILED",
    mriStudyIds: ["mri-K-2044-T0"],
    aiProcessingJobIds: ["aijob-K-2044-01"],
    biomarkerOutputIds: ["bio-K-2044-segqc-01"],
    quantitativeReportIds: [],
    protocolCompletenessAssessmentIds: ["proto-K-2044-01"],
    imageQualityAssessmentIds: ["imgqc-K-2044-01"],
    structuredVisualAssessmentIds: ["sva-K-2044-01"],
    anonymizedId: "R-1210",
    patientName: "Reza Moradi",
    age: 75,
    ageGroup: "75–79",
    sex: "Male",
    scanDate: "2026-06-14",
    caseStatus: "Image quality issue",
    mriStatus: "Quality issue",
    intakeStatus: "Complete",
    aiStatus: "Blocked",
    radiologistStatus: "Needs quality review",
    neurologistStatus: "Not ready",
    reportStatus: "Not available",
    patientSummaryStatus: "Not prepared",
    pdfReleaseStatus: "Not approved",
    releaseStatus: "Not released",
    followUpStatus: "Not scheduled",
    nextAction: "Resolve image quality issue",
    currentOwnerRole: "Radiologist",
    blocker: "Motion artifact affects processing readiness",
    assignedRadiologist: "Dr. M. Farzan",
    assignedNeurologist: "Unassigned",
    imageQuality: "Needs review",
    memoryComplaint: "Referral notes indicate recent memory concerns.",
    cognitiveHistory: "Clinical intake available.",
    cognitiveScore: "Not added",
    caregiverObservation: "Not added",
    keyFindings: ["No AI output available", "Motion artifact requires review"],
    findings: [],
    timeline: [
      { label: "Case created", detail: "Referral received", date: "Jun 13", patientSafe: true },
      { label: "MRI received", detail: "Study matched", date: "Jun 14", patientSafe: true },
      { label: "Image quality issue", detail: "Specialist review required", date: "Today", tone: "attention" },
    ],
    outputVersion: "No AI output",
    reportVersion: "No report",
    amendmentStatus: "Not available",
    researchEligible: false,
    researchConsent: "Not requested",
    consentScope: "Not available",
    anonymizationStatus: "Not prepared",
    anonymizationMethod: "Not available",
    researchTimepoint: "Not available",
    datasetVersion: "Not prepared",
    exportVersion: "Blocked",
    withdrawalStatus: "Not applicable",
    longitudinal: false,
    patientSafeStatus: "Your MRI needs additional review",
    patientNextAction: "The clinic will contact you if a new image is required.",
    patientFormProgress: 100,
    consentStatus: "Complete",
    radiologistComment: "Motion artifact may affect segmentation reliability.",
    physicianNote: "",
  },
  {
    id: "K-2045",
    state: "PATIENT_INFORMATION_PENDING",
    anonymizedId: "R-1222",
    patientName: "Sara Ahmadi",
    age: 69,
    ageGroup: "65–69",
    sex: "Female",
    scanDate: "Not received",
    caseStatus: "Waiting for MRI",
    mriStatus: "Missing",
    intakeStatus: "Incomplete",
    aiStatus: "Not started",
    radiologistStatus: "Not ready",
    neurologistStatus: "Not ready",
    reportStatus: "Not available",
    patientSummaryStatus: "Not prepared",
    pdfReleaseStatus: "Not approved",
    releaseStatus: "Not released",
    followUpStatus: "Not scheduled",
    nextAction: "Request MRI and complete intake",
    currentOwnerRole: "Operations",
    blocker: "MRI and two intake fields missing",
    assignedRadiologist: "Unassigned",
    assignedNeurologist: "Unassigned",
    imageQuality: "Not available",
    memoryComplaint: "Patient reports increasing reliance on reminders.",
    cognitiveHistory: "Two intake fields remain incomplete.",
    cognitiveScore: "Not added",
    caregiverObservation: "Draft saved",
    keyFindings: [],
    findings: [],
    timeline: [
      { label: "Case created", detail: "Secure patient link sent", date: "Jun 14", patientSafe: true },
      { label: "Information started", detail: "Intake is 72% complete", date: "Today", patientSafe: true },
    ],
    outputVersion: "No AI output",
    reportVersion: "No report",
    amendmentStatus: "Not available",
    researchEligible: false,
    researchConsent: "Not requested",
    consentScope: "Not available",
    anonymizationStatus: "Not prepared",
    anonymizationMethod: "Not available",
    researchTimepoint: "Not available",
    datasetVersion: "Not prepared",
    exportVersion: "Blocked",
    withdrawalStatus: "Not applicable",
    longitudinal: false,
    patientSafeStatus: "Please complete your information",
    patientNextAction: "Complete your information and upload the requested MRI.",
    patientFormProgress: 72,
    consentStatus: "Action required",
    radiologistComment: "",
    physicianNote: "",
  },
];

export const initialCases: KioCase[] = rawInitialCases.map(withDerivedCaseFields);

export const mriStudyReferences: MriStudyReference[] = [
  {
    id: "mri-K-2041-T0",
    caseId: "K-2041",
    studyDate: "2026-06-11",
    modality: "MRI",
    protocolName: "Alzheimer structural MRI MVP",
    source: "pacs",
    requiredSequences: ["3D T1 MPRAGE"],
    availableSequences: ["3D T1 MPRAGE", "T2 FLAIR"],
    missingSequences: [],
    qualityStatus: "passed",
    scannerVendor: "Siemens",
    scannerFieldStrength: "3T",
    inputSeriesIds: ["SER-K2041-T1-001"],
    notes: "Lightweight study reference; full DICOM metadata is out of scope.",
    createdAt: "2026-06-11T09:30:00Z",
  },
  {
    id: "mri-K-2042-T0",
    caseId: "K-2042",
    studyDate: "2026-06-13",
    modality: "MRI",
    protocolName: "Alzheimer structural MRI MVP",
    source: "pacs",
    requiredSequences: ["3D T1 MPRAGE"],
    availableSequences: ["3D T1 MPRAGE"],
    missingSequences: [],
    qualityStatus: "passed",
    scannerVendor: "GE",
    scannerFieldStrength: "3T",
    inputSeriesIds: ["SER-K2042-T1-001"],
    createdAt: "2026-06-13T10:10:00Z",
  },
  {
    id: "mri-K-2043-T0",
    caseId: "K-2043",
    studyDate: "2025-05-25",
    modality: "MRI",
    protocolName: "Alzheimer baseline structural MRI MVP",
    source: "prototype_fixture",
    requiredSequences: ["3D T1 MPRAGE"],
    availableSequences: ["3D T1 MPRAGE"],
    missingSequences: [],
    qualityStatus: "passed",
    scannerVendor: "Philips",
    scannerFieldStrength: "3T",
    inputSeriesIds: ["SER-K2043-T1-001"],
    notes: "Baseline reference for relative longitudinal comparison.",
    createdAt: "2025-05-25T08:30:00Z",
  },
  {
    id: "mri-K-2043-T1",
    caseId: "K-2043",
    studyDate: "2026-05-24",
    modality: "MRI",
    protocolName: "Alzheimer longitudinal structural MRI MVP",
    source: "pacs",
    requiredSequences: ["3D T1 MPRAGE"],
    availableSequences: ["3D T1 MPRAGE"],
    missingSequences: [],
    qualityStatus: "passed_with_limitations",
    scannerVendor: "Philips",
    scannerFieldStrength: "3T",
    inputSeriesIds: ["SER-K2043-T1-002"],
    notes: "Follow-up pair suitable for relative interval comparison.",
    createdAt: "2026-05-24T08:45:00Z",
  },
  {
    id: "mri-K-2044-T0",
    caseId: "K-2044",
    studyDate: "2026-06-14",
    modality: "MRI",
    protocolName: "Alzheimer structural MRI MVP",
    source: "pacs",
    requiredSequences: ["3D T1 MPRAGE"],
    availableSequences: ["3D T1 MPRAGE"],
    missingSequences: [],
    qualityStatus: "failed",
    scannerVendor: "Unknown",
    scannerFieldStrength: "unknown",
    inputSeriesIds: ["SER-K2044-T1-001"],
    notes: "Motion artifact blocks normal quantitative processing.",
    createdAt: "2026-06-14T12:00:00Z",
  },
];

export const aiProcessingJobs: AiProcessingJob[] = [
  {
    id: "aijob-K-2041-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    jobType: "initial_processing",
    status: "qc_passed",
    requestedAt: "2026-06-11T09:34:00Z",
    startedAt: "2026-06-11T09:36:00Z",
    completedAt: "2026-06-11T09:48:00Z",
    requestedByRole: "operations_coordinator",
    pipelineName: "Kio NeuroQuant MVP",
    pipelineVersion: "pipeline-2026.06",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    inputSeries: ["SER-K2041-T1-001"],
    outputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    qcStatus: "qc_passed",
    auditEventIds: [],
  },
  {
    id: "aijob-K-2042-01",
    caseId: "K-2042",
    mriStudyId: "mri-K-2042-T0",
    jobType: "initial_processing",
    status: "qc_pending",
    requestedAt: "2026-06-13T10:15:00Z",
    startedAt: "2026-06-13T10:17:00Z",
    completedAt: "2026-06-13T10:30:00Z",
    requestedByRole: "operations_coordinator",
    pipelineName: "Kio NeuroQuant MVP",
    pipelineVersion: "pipeline-2026.06",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    inputSeries: ["SER-K2042-T1-001"],
    outputIds: ["bio-K-2042-vol-01"],
    qcStatus: "qc_pending",
    auditEventIds: [],
  },
  {
    id: "aijob-K-2043-long-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    jobType: "longitudinal_processing",
    status: "qc_passed_with_limitations",
    requestedAt: "2026-05-24T08:49:00Z",
    startedAt: "2026-05-24T08:52:00Z",
    completedAt: "2026-05-24T09:05:00Z",
    requestedByRole: "operations_coordinator",
    pipelineName: "Kio NeuroQuant MVP",
    pipelineVersion: "pipeline-2026.06",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    inputSeries: ["SER-K2043-T1-002"],
    outputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    qcStatus: "qc_passed_with_limitations",
    auditEventIds: [],
  },
  {
    id: "aijob-K-2044-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    jobType: "initial_processing",
    status: "qc_failed",
    requestedAt: "2026-06-14T12:05:00Z",
    startedAt: "2026-06-14T12:07:00Z",
    failedAt: "2026-06-14T12:11:00Z",
    requestedByRole: "operations_coordinator",
    pipelineName: "Kio NeuroQuant MVP",
    pipelineVersion: "pipeline-2026.06",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    inputSeries: ["SER-K2044-T1-001"],
    outputIds: ["bio-K-2044-segqc-01"],
    failureReason: "Motion artifact affected segmentation reliability.",
    qcStatus: "qc_failed",
    auditEventIds: [],
  },
];

export const segmentationQcFixtures: SegmentationQc[] = [
  {
    id: "segqc-K-2041-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    aiProcessingJobId: "aijob-K-2041-01",
    status: "passed",
    technicalReviewerRole: "mri_scientist_ai_qa",
    technicalReviewedAt: "2026-06-11T10:02:00Z",
    radiologistAcceptanceStatus: "accepted",
    radiologistAcceptedAt: "2026-06-12T08:15:00Z",
    issues: [],
    limitations: [],
    reprocessingRecommended: false,
    suitableForQuantitativeReview: true,
    suitableForPhysicianHandoff: true,
  },
  {
    id: "segqc-K-2044-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    aiProcessingJobId: "aijob-K-2044-01",
    status: "failed",
    technicalReviewerRole: "mri_scientist_ai_qa",
    technicalReviewedAt: "2026-06-14T12:14:00Z",
    radiologistAcceptanceStatus: "rejected",
    issues: [{ code: "MOTION_ARTIFACT", label: "Motion artifact affects hippocampal segmentation", severity: "blocking", region: "hippocampus" }],
    limitations: ["Segmentation masks suppressed from physician and patient-facing views."],
    reprocessingRecommended: true,
    suitableForQuantitativeReview: false,
    suitableForPhysicianHandoff: false,
  },
];

export const biomarkerOutputs: BiomarkerOutput[] = [
  {
    id: "bio-K-2041-vol-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    aiProcessingJobId: "aijob-K-2041-01",
    outputType: "volumetry",
    status: "radiologist_reviewed",
    createdAt: "2026-06-11T09:49:00Z",
    version: "output 03",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    segmentationQc: segmentationQcFixtures[0],
    reviewStatus: "radiologist_reviewed",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-06-12T08:20:00Z",
    limitations: ["Decision-support evidence only; clinical interpretation remains physician-owned."],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: true,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2041-l-hip", outputId: "bio-K-2041-vol-01", metricKey: "left_hippocampus_volume", label: "Left hippocampus volume", category: "hippocampal", region: "Left hippocampus", laterality: "left", measurementType: "volume", value: 2.41, unit: "cm3", percentile: 4, zScore: -1.85, referenceRange: { label: "Below reference", population: "age/sex reference" }, comparisonLabel: "Below reference", validityStatus: "valid", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: [], displayPriority: 1, patientVisible: false },
      { id: "met-K2041-r-hip", outputId: "bio-K-2041-vol-01", metricKey: "right_hippocampus_volume", label: "Right hippocampus volume", category: "hippocampal", region: "Right hippocampus", laterality: "right", measurementType: "volume", value: 2.58, unit: "cm3", percentile: 8, zScore: -1.55, referenceRange: { label: "Lower reference range", population: "age/sex reference" }, comparisonLabel: "Lower reference range", validityStatus: "valid", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: [], displayPriority: 2, patientVisible: false },
      { id: "met-K2041-latvent", outputId: "bio-K-2041-vol-01", metricKey: "lateral_ventricles_volume", label: "Lateral ventricles volume", category: "ventricular", region: "Lateral ventricles", laterality: "bilateral", measurementType: "volume", value: 37.2, unit: "cm3", percentile: 91, referenceRange: { label: "Upper reference range", population: "age/sex reference" }, comparisonLabel: "Upper reference range", validityStatus: "valid", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: [], displayPriority: 3, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2041-cort-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    aiProcessingJobId: "aijob-K-2041-01",
    outputType: "corticometry",
    status: "radiologist_reviewed",
    createdAt: "2026-06-11T09:50:00Z",
    version: "cort output 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    reviewStatus: "radiologist_reviewed",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-06-12T08:20:00Z",
    limitations: ["Corticometry display support exists; advanced dashboards remain out of PR3 scope."],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: true,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2041-entorhinal-thick", outputId: "bio-K-2041-cort-01", metricKey: "entorhinal_cortical_thickness", label: "Entorhinal cortical thickness", category: "entorhinal", region: "Entorhinal cortex", laterality: "bilateral", measurementType: "cortical_thickness", value: 2.71, unit: "mm", percentile: 11, referenceRange: { label: "Lower reference range" }, comparisonLabel: "Lower reference range", validityStatus: "valid_with_limitations", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: ["Prototype metric; no advanced dashboard in PR3."], displayPriority: 4, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2041-ad-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    aiProcessingJobId: "aijob-K-2041-01",
    outputType: "ad_summary",
    status: "radiologist_reviewed",
    createdAt: "2026-06-11T09:51:00Z",
    version: "ad summary 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    reviewStatus: "radiologist_reviewed",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-06-12T08:20:00Z",
    limitations: ["HOC is represented as reviewed evidence, not diagnosis."],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: true,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2041-hoc", outputId: "bio-K-2041-ad-01", metricKey: "hippocampal_occupancy_score", label: "HOC / hippocampal occupancy score", category: "ad_relevant", region: "Hippocampal occupancy", laterality: "bilateral", measurementType: "score", value: 0.63, unit: "score", percentile: 7, referenceRange: { label: "Lower reference range" }, comparisonLabel: "Lower reference range", validityStatus: "valid", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: ["Decision-support metric; must be interpreted by physician."], displayPriority: 5, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2042-vol-01",
    caseId: "K-2042",
    mriStudyId: "mri-K-2042-T0",
    aiProcessingJobId: "aijob-K-2042-01",
    outputType: "volumetry",
    status: "ready_for_radiologist_review",
    createdAt: "2026-06-13T10:31:00Z",
    version: "output 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    reviewStatus: "radiologist_review_pending",
    limitations: [],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: false,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2042-temporal", outputId: "bio-K-2042-vol-01", metricKey: "temporal_lobe_volume", label: "Temporal lobe volume", category: "temporal", region: "Temporal lobe", laterality: "bilateral", measurementType: "volume", value: 101.8, unit: "cm3", percentile: 9, referenceRange: { label: "Lower reference range" }, comparisonLabel: "Lower reference range", validityStatus: "qc_pending", visibilityStatus: "radiologist_visible", suppressed: false, limitations: ["Not physician-visible until radiologist review completes."], displayPriority: 1, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2043-vol-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    aiProcessingJobId: "aijob-K-2043-long-01",
    outputType: "volumetry",
    status: "radiologist_reviewed",
    createdAt: "2026-05-24T09:04:00Z",
    version: "follow-up volumetry 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    reviewStatus: "radiologist_reviewed",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-05-25T11:00:00Z",
    limitations: ["Follow-up volumetry used only with comparability context."],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: true,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2043-whole-brain", outputId: "bio-K-2043-vol-01", metricKey: "whole_brain_volume", label: "Whole brain volume", category: "global_brain", region: "Whole brain", laterality: "total", measurementType: "volume", value: 1076, unit: "cm3", percentile: 45, referenceRange: { label: "Within reference" }, comparisonLabel: "Within reference", validityStatus: "valid", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: [], displayPriority: 2, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2043-long-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    aiProcessingJobId: "aijob-K-2043-long-01",
    outputType: "longitudinal_comparison",
    status: "radiologist_reviewed",
    createdAt: "2026-05-24T09:06:00Z",
    version: "longitudinal output 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    reviewStatus: "radiologist_reviewed",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-05-25T11:00:00Z",
    limitations: ["Relative interval comparison only; follow-up decisions remain physician-owned."],
    suitableForRadiologistReview: true,
    suitableForPhysicianReview: true,
    patientVisible: false,
    researchEligible: true,
    metrics: [
      { id: "met-K2043-hip-change", outputId: "bio-K-2043-long-01", metricKey: "hippocampal_volume_change_percent", label: "Hippocampal volume change", category: "longitudinal", region: "Hippocampus", laterality: "bilateral", measurementType: "percent_change", value: -0.8, unit: "percent", changePercent: -0.8, baselineValue: 5.62, followUpValue: 5.58, annualizedChange: -0.8, comparisonLabel: "Comparable to baseline", validityStatus: "valid_with_limitations", visibilityStatus: "physician_visible_after_review", suppressed: false, limitations: ["Scanner/protocol comparability reviewed."], displayPriority: 1, patientVisible: false },
    ],
  },
  {
    id: "bio-K-2044-segqc-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    aiProcessingJobId: "aijob-K-2044-01",
    outputType: "segmentation_qc",
    status: "suppressed",
    createdAt: "2026-06-14T12:15:00Z",
    version: "segmentation qc 01",
    algorithmVersion: "AI-v1.2",
    referenceDatasetVersion: "Ref-AD-MRI-2026.1",
    segmentationQc: segmentationQcFixtures[1],
    reviewStatus: "suppressed",
    reviewedByRole: "mri_scientist_ai_qa",
    reviewedAt: "2026-06-14T12:14:00Z",
    limitations: ["Segmentation and quantitative metrics suppressed because QC failed."],
    suppressionReason: "Motion artifact affected segmentation reliability.",
    suitableForRadiologistReview: false,
    suitableForPhysicianReview: false,
    patientVisible: false,
    researchEligible: false,
    metrics: [
      { id: "met-K2044-qc", outputId: "bio-K-2044-segqc-01", metricKey: "segmentation_qc_status", label: "Segmentation QC status", category: "technical_qc", region: "Whole study", laterality: "not_applicable", measurementType: "score", value: null, validityStatus: "suppressed", visibilityStatus: "technical_only", suppressed: true, suppressionReason: "QC failed", limitations: ["No clinical or patient-facing use."], displayPriority: 1, patientVisible: false },
    ],
  },
];

export const quantitativeReportPlaceholders: QuantitativeReportPlaceholder[] = [
  {
    id: "qreport-K-2041-rad-summary-01",
    caseId: "K-2041",
    reportTypeId: "radiologist_reviewed_quantitative_summary",
    sourceOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    status: "reviewed",
    version: "Report draft v0.3",
    createdAt: "2026-06-12T08:30:00Z",
    structuredDataRequired: true,
    pdfRenderable: true,
    patientVisible: false,
    notes: "Report taxonomy placeholder only; full lifecycle is not implemented in PR3.",
  },
  {
    id: "qreport-K-2042-tech-01",
    caseId: "K-2042",
    reportTypeId: "technical_quantitative_report",
    sourceOutputIds: ["bio-K-2042-vol-01"],
    status: "ready_for_review",
    version: "Report draft v0.1",
    createdAt: "2026-06-13T10:35:00Z",
    structuredDataRequired: true,
    pdfRenderable: false,
    patientVisible: false,
  },
  {
    id: "qreport-K-2043-phys-evidence-01",
    caseId: "K-2043",
    reportTypeId: "physician_facing_evidence_summary",
    sourceOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    status: "reviewed",
    version: "Final report v1.0",
    createdAt: "2026-05-27T13:30:00Z",
    structuredDataRequired: true,
    pdfRenderable: false,
    patientVisible: false,
    notes: "Physician-facing evidence summary is distinct from patient-safe summary.",
  },
];

export const protocolCompletenessAssessments: ProtocolCompletenessAssessment[] = [
  {
    id: "proto-K-2041-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    assessedByRole: "radiologist",
    assessedAt: "2026-06-12T08:02:00Z",
    status: "complete",
    requiredSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI or T2*"],
    availableSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI"],
    missingSequences: [],
    optionalSequences: ["Coronal T2 hippocampal sequence"],
    limitations: [],
    suitableForVisualAssessment: true,
    suitableForQuantitativeProcessing: true,
    notes: "Protocol supports structured dementia MRI visual review.",
  },
  {
    id: "proto-K-2042-01",
    caseId: "K-2042",
    mriStudyId: "mri-K-2042-T0",
    assessedByRole: "radiologist",
    assessedAt: "2026-06-13T10:50:00Z",
    status: "complete_with_limitations",
    requiredSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI or T2*"],
    availableSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC"],
    missingSequences: ["SWI or T2*"],
    optionalSequences: [],
    limitations: ["Susceptibility assessment limited because SWI/T2* is not available."],
    suitableForVisualAssessment: true,
    suitableForQuantitativeProcessing: true,
  },
  {
    id: "proto-K-2043-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    assessedByRole: "neuroradiologist",
    assessedAt: "2026-05-25T10:05:00Z",
    status: "complete_with_limitations",
    requiredSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI or T2*"],
    availableSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI"],
    missingSequences: [],
    optionalSequences: ["Prior comparable MRI"],
    limitations: ["Longitudinal comparability reviewed as relative interval evidence only."],
    suitableForVisualAssessment: true,
    suitableForQuantitativeProcessing: true,
  },
  {
    id: "proto-K-2044-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    assessedByRole: "mri_scientist_ai_qa",
    assessedAt: "2026-06-14T12:10:00Z",
    status: "failed",
    requiredSequences: ["3D T1 MPRAGE", "T2 FLAIR", "DWI/ADC", "SWI or T2*"],
    availableSequences: ["3D T1 MPRAGE"],
    missingSequences: ["T2 FLAIR", "DWI/ADC", "SWI or T2*"],
    optionalSequences: [],
    limitations: ["Required dementia review sequences are incomplete."],
    suitableForVisualAssessment: false,
    suitableForQuantitativeProcessing: false,
    notes: "Operations should coordinate corrected imaging; no clinical interpretation is created here.",
  },
];

export const imageQualityAssessments: ImageQualityAssessment[] = [
  {
    id: "imgqc-K-2041-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-06-12T08:05:00Z",
    status: "passed",
    motionArtifact: "none",
    coverageIssue: "none",
    sequenceQualityIssues: [],
    majorLimitation: false,
    limitations: [],
    suitableForRadiologistReview: true,
    suitableForAiProcessing: true,
    requiresRescan: false,
    requiresReprocessing: false,
  },
  {
    id: "imgqc-K-2042-01",
    caseId: "K-2042",
    mriStudyId: "mri-K-2042-T0",
    reviewedByRole: "radiologist",
    reviewedAt: "2026-06-13T10:55:00Z",
    status: "passed_with_limitations",
    motionArtifact: "mild",
    coverageIssue: "none",
    sequenceQualityIssues: [{ sequence: "3D T1 MPRAGE", issue: "Mild motion", severity: "minor" }],
    majorLimitation: false,
    limitations: ["Mild motion noted; radiologist review required before handoff."],
    suitableForRadiologistReview: true,
    suitableForAiProcessing: true,
    requiresRescan: false,
    requiresReprocessing: false,
  },
  {
    id: "imgqc-K-2043-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    reviewedByRole: "neuroradiologist",
    reviewedAt: "2026-05-25T10:10:00Z",
    status: "passed_with_limitations",
    motionArtifact: "none",
    coverageIssue: "minor",
    sequenceQualityIssues: [{ sequence: "Prior MRI comparison", issue: "Scanner/protocol interval difference", severity: "minor" }],
    majorLimitation: false,
    limitations: ["Comparison is suitable for high-level follow-up context, not automated progression diagnosis."],
    suitableForRadiologistReview: true,
    suitableForAiProcessing: true,
    requiresRescan: false,
    requiresReprocessing: false,
  },
  {
    id: "imgqc-K-2044-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    reviewedByRole: "mri_scientist_ai_qa",
    reviewedAt: "2026-06-14T12:12:00Z",
    status: "rescan_recommended",
    motionArtifact: "severe",
    coverageIssue: "major",
    sequenceQualityIssues: [{ sequence: "3D T1 MPRAGE", issue: "Motion artifact affects visual and quantitative reliability", severity: "blocking" }],
    majorLimitation: true,
    limitations: ["Structured visual review is blocked by image quality."],
    suitableForRadiologistReview: false,
    suitableForAiProcessing: false,
    requiresRescan: true,
    requiresReprocessing: false,
    notes: "Technical QC only; final clinical interpretation is not created.",
  },
];

export const structuredVisualAssessments: StructuredVisualAssessment[] = [
  {
    id: "sva-K-2041-01",
    caseId: "K-2041",
    mriStudyId: "mri-K-2041-T0",
    radiologistReviewId: "radrev-K-2041-01",
    status: "completed",
    createdAt: "2026-06-12T08:06:00Z",
    updatedAt: "2026-06-12T08:18:00Z",
    assessedByRole: "radiologist",
    assessedAt: "2026-06-12T08:18:00Z",
    protocolCompletenessAssessmentId: "proto-K-2041-01",
    imageQualityAssessmentId: "imgqc-K-2041-01",
    visualScores: [
      { id: "score-K2041-mta-l", scale: "mta", label: "MTA left", value: 2, side: "left", rangeMin: 0, rangeMax: 4, sequenceReference: "3D T1 MPRAGE", confidence: "high", limitations: [], required: true, completed: true },
      { id: "score-K2041-mta-r", scale: "mta", label: "MTA right", value: 2, side: "right", rangeMin: 0, rangeMax: 4, sequenceReference: "3D T1 MPRAGE", confidence: "high", limitations: [], required: true, completed: true },
      { id: "score-K2041-fazekas", scale: "fazekas", label: "Fazekas white matter score", value: 1, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "T2 FLAIR", confidence: "high", limitations: [], required: true, completed: true },
      { id: "score-K2041-koedam", scale: "koedam_posterior_atrophy", label: "Koedam posterior atrophy", value: 1, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "3D T1 MPRAGE", confidence: "moderate", limitations: [], required: true, completed: true },
      { id: "score-K2041-gca", scale: "gca", label: "Global cortical atrophy", value: 1, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "3D T1 MPRAGE", confidence: "high", limitations: [], required: true, completed: true },
    ],
    atrophyFindings: { globalCorticalAtrophy: "mild", medialTemporalAtrophy: "moderate", frontalAtrophy: "mild", parietalPosteriorAtrophy: "mild", temporalAtrophy: "moderate", asymmetry: "none" },
    vascularFindings: { whiteMatterHyperintensities: "mild", smallVesselDisease: "mild", lacunarInfarcts: "absent", strategicInfarcts: "absent", chronicInfarcts: "absent", enlargedPerivascularSpaces: "mild", vascularBurdenSummary: "Mild white matter burden; no strategic infarct flagged.", fazekasScoreReference: "score-K2041-fazekas" },
    diffusionFindings: { acuteDiffusionRestriction: "absent", dwiAdcAdequacy: "adequate", acuteInfarctFlag: false, limitationNotes: [] },
    susceptibilityFindings: { microbleeds: "absent", superficialSiderosis: "absent", priorHemorrhageFlag: false, swiT2StarAdequacy: "adequate", limitationNotes: [] },
    hydrocephalusFindings: { ventriculomegalyFlag: true, disproportionateCsfSpacesFlag: false, nphConcernFlag: false, limitationNotes: [] },
    incidentalFindings: [],
    limitations: ["Structured visual assessment is imaging evidence and not a diagnosis."],
    radiologistImpression: "Structured dementia MRI visual review completed; imaging evidence is suitable for physician clinical synthesis.",
    handoffNote: "Review visual atrophy pattern alongside quantitative evidence and clinical context.",
    suitableForPhysicianHandoff: true,
    patientVisible: false,
    researchEligible: true,
  },
  {
    id: "sva-K-2042-01",
    caseId: "K-2042",
    mriStudyId: "mri-K-2042-T0",
    radiologistReviewId: "radrev-K-2042-01",
    status: "in_progress",
    createdAt: "2026-06-13T10:56:00Z",
    updatedAt: "2026-06-13T10:56:00Z",
    assessedByRole: "radiologist",
    protocolCompletenessAssessmentId: "proto-K-2042-01",
    imageQualityAssessmentId: "imgqc-K-2042-01",
    visualScores: [
      { id: "score-K2042-mta-l", scale: "mta", label: "MTA left", value: null, side: "left", rangeMin: 0, rangeMax: 4, sequenceReference: "3D T1 MPRAGE", confidence: "not_assessed", limitations: ["Pending radiologist visual review."], required: true, completed: false },
      { id: "score-K2042-fazekas", scale: "fazekas", label: "Fazekas white matter score", value: null, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "T2 FLAIR", confidence: "not_assessed", limitations: ["Pending radiologist visual review."], required: true, completed: false },
    ],
    atrophyFindings: { globalCorticalAtrophy: "not_assessed", medialTemporalAtrophy: "not_assessed", frontalAtrophy: "not_assessed", parietalPosteriorAtrophy: "not_assessed", temporalAtrophy: "not_assessed", asymmetry: "not_assessed" },
    vascularFindings: { whiteMatterHyperintensities: "not_assessed", smallVesselDisease: "not_assessed", lacunarInfarcts: "not_assessed", strategicInfarcts: "not_assessed", chronicInfarcts: "not_assessed", enlargedPerivascularSpaces: "not_assessed", vascularBurdenSummary: "Pending structured visual review." },
    diffusionFindings: { acuteDiffusionRestriction: "not_assessed", dwiAdcAdequacy: "adequate", acuteInfarctFlag: false, limitationNotes: [] },
    susceptibilityFindings: { microbleeds: "not_assessed", superficialSiderosis: "not_assessed", priorHemorrhageFlag: false, swiT2StarAdequacy: "not_available", limitationNotes: ["SWI/T2* not available."] },
    hydrocephalusFindings: { ventriculomegalyFlag: false, disproportionateCsfSpacesFlag: false, nphConcernFlag: false, limitationNotes: [] },
    incidentalFindings: [],
    limitations: ["SWI/T2* not available; susceptibility review limited."],
    radiologistImpression: "",
    handoffNote: "",
    suitableForPhysicianHandoff: false,
    patientVisible: false,
    researchEligible: false,
  },
  {
    id: "sva-K-2043-01",
    caseId: "K-2043",
    mriStudyId: "mri-K-2043-T1",
    radiologistReviewId: "radrev-K-2043-01",
    status: "completed_with_limitations",
    createdAt: "2026-05-25T10:12:00Z",
    updatedAt: "2026-05-25T10:28:00Z",
    assessedByRole: "neuroradiologist",
    assessedAt: "2026-05-25T10:28:00Z",
    protocolCompletenessAssessmentId: "proto-K-2043-01",
    imageQualityAssessmentId: "imgqc-K-2043-01",
    visualScores: [
      { id: "score-K2043-mta-b", scale: "mta", label: "MTA bilateral", value: 1, side: "bilateral", rangeMin: 0, rangeMax: 4, sequenceReference: "3D T1 MPRAGE", confidence: "moderate", limitations: ["Relative comparison only."], required: true, completed: true },
      { id: "score-K2043-fazekas", scale: "fazekas", label: "Fazekas white matter score", value: 1, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "T2 FLAIR", confidence: "high", limitations: [], required: true, completed: true },
      { id: "score-K2043-koedam", scale: "koedam_posterior_atrophy", label: "Koedam posterior atrophy", value: 0, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "3D T1 MPRAGE", confidence: "moderate", limitations: [], required: true, completed: true },
      { id: "score-K2043-gca", scale: "gca", label: "Global cortical atrophy", value: 1, side: "global", rangeMin: 0, rangeMax: 3, sequenceReference: "3D T1 MPRAGE", confidence: "high", limitations: [], required: true, completed: true },
    ],
    atrophyFindings: { globalCorticalAtrophy: "mild", medialTemporalAtrophy: "mild", frontalAtrophy: "none", parietalPosteriorAtrophy: "none", temporalAtrophy: "mild", asymmetry: "none" },
    vascularFindings: { whiteMatterHyperintensities: "mild", smallVesselDisease: "mild", lacunarInfarcts: "absent", strategicInfarcts: "absent", chronicInfarcts: "absent", enlargedPerivascularSpaces: "none", vascularBurdenSummary: "Mild vascular burden; no strategic lesion flagged.", fazekasScoreReference: "score-K2043-fazekas" },
    diffusionFindings: { acuteDiffusionRestriction: "absent", dwiAdcAdequacy: "adequate", acuteInfarctFlag: false, limitationNotes: [] },
    susceptibilityFindings: { microbleeds: "absent", superficialSiderosis: "absent", priorHemorrhageFlag: false, swiT2StarAdequacy: "adequate", limitationNotes: [] },
    hydrocephalusFindings: { ventriculomegalyFlag: false, disproportionateCsfSpacesFlag: false, nphConcernFlag: false, limitationNotes: [] },
    incidentalFindings: [],
    limitations: ["Longitudinal visual review is suitable for context, not autonomous progression diagnosis."],
    radiologistImpression: "Visual review completed with longitudinal comparability limitation noted.",
    handoffNote: "Use as reviewed imaging context for follow-up clinical synthesis.",
    suitableForPhysicianHandoff: true,
    patientVisible: false,
    researchEligible: true,
  },
  {
    id: "sva-K-2044-01",
    caseId: "K-2044",
    mriStudyId: "mri-K-2044-T0",
    radiologistReviewId: "radrev-K-2044-01",
    status: "blocked_by_image_quality",
    createdAt: "2026-06-14T12:15:00Z",
    updatedAt: "2026-06-14T12:15:00Z",
    assessedByRole: "radiologist",
    protocolCompletenessAssessmentId: "proto-K-2044-01",
    imageQualityAssessmentId: "imgqc-K-2044-01",
    visualScores: [],
    atrophyFindings: { globalCorticalAtrophy: "limited_by_quality", medialTemporalAtrophy: "limited_by_quality", frontalAtrophy: "limited_by_quality", parietalPosteriorAtrophy: "limited_by_quality", temporalAtrophy: "limited_by_quality", asymmetry: "not_assessed" },
    vascularFindings: { whiteMatterHyperintensities: "limited_by_quality", smallVesselDisease: "limited_by_quality", lacunarInfarcts: "not_assessed", strategicInfarcts: "not_assessed", chronicInfarcts: "not_assessed", enlargedPerivascularSpaces: "not_assessed", vascularBurdenSummary: "Blocked by image quality." },
    diffusionFindings: { acuteDiffusionRestriction: "limited_by_quality", dwiAdcAdequacy: "not_available", acuteInfarctFlag: false, limitationNotes: ["DWI/ADC not available in current study."] },
    susceptibilityFindings: { microbleeds: "not_assessed", superficialSiderosis: "not_assessed", priorHemorrhageFlag: false, swiT2StarAdequacy: "not_available", limitationNotes: ["SWI/T2* not available."] },
    hydrocephalusFindings: { ventriculomegalyFlag: false, disproportionateCsfSpacesFlag: false, nphConcernFlag: false, limitationNotes: ["Assessment blocked by incomplete protocol and motion artifact."] },
    incidentalFindings: [],
    limitations: ["Structured visual assessment blocked; corrected imaging is required."],
    radiologistImpression: "",
    handoffNote: "",
    suitableForPhysicianHandoff: false,
    patientVisible: false,
    researchEligible: false,
  },
];

export const radiologistImagingHandoffs: RadiologistImagingHandoff[] = [
  {
    id: "handoff-K-2041-01",
    caseId: "K-2041",
    structuredVisualAssessmentId: "sva-K-2041-01",
    biomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    status: "ready_for_physician_review",
    createdByRole: "radiologist",
    createdAt: "2026-06-12T08:25:00Z",
    imagingSummary: "Structured visual MRI review and quantitative evidence are ready for physician clinical synthesis.",
    limitations: ["Imaging handoff is not final diagnosis."],
    openQuestions: [],
    recommendedNextStep: "Physician clinical synthesis with patient context.",
    suitableForPhysicianReview: true,
    patientVisible: false,
  },
  {
    id: "handoff-K-2043-01",
    caseId: "K-2043",
    structuredVisualAssessmentId: "sva-K-2043-01",
    biomarkerOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    status: "completed",
    createdByRole: "neuroradiologist",
    createdAt: "2026-05-25T10:35:00Z",
    imagingSummary: "Follow-up visual review completed with comparability limitation noted.",
    limitations: ["Follow-up comparison is imaging context only."],
    openQuestions: [],
    recommendedNextStep: "Physician review in clinical follow-up context.",
    suitableForPhysicianReview: true,
    patientVisible: false,
  },
];

export const structuredReports: StructuredReport[] = [
  {
    id: "sreport-K-2041-rad-quant-01",
    caseId: "K-2041",
    reportType: "radiologist_reviewed_quantitative_summary",
    status: "reviewed",
    createdAt: "2026-06-12T08:28:00Z",
    updatedAt: "2026-06-12T08:34:00Z",
    createdByRole: "radiologist",
    primaryOwnerRole: "radiologist",
    intendedAudience: "radiologist",
    sourceMriStudyIds: ["mri-K-2041-T0"],
    sourceBiomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    sourceStructuredVisualAssessmentIds: [],
    sourceRadiologistHandoffIds: ["handoff-K-2041-01"],
    evidenceReferences: [
      { id: "eref-K2041-vol-output", reportId: "sreport-K-2041-rad-quant-01", sourceType: "biomarker_output", sourceId: "bio-K-2041-vol-01", sourceVersion: "output 03", includedByRole: "radiologist", includedAt: "2026-06-12T08:28:00Z", visibility: "radiologist", limitations: ["Decision-support evidence only."], evidenceSummary: "Reviewed volumetry output included by reference.", patientVisible: false },
      { id: "eref-K2041-hoc-metric", reportId: "sreport-K-2041-rad-quant-01", sourceType: "biomarker_metric", sourceId: "met-K2041-hoc", sourceVersion: "ad summary 01", includedByRole: "radiologist", includedAt: "2026-06-12T08:28:00Z", visibility: "radiologist", limitations: ["HOC is not diagnosis."], evidenceSummary: "AD-relevant HOC metric referenced for radiologist review.", patientVisible: false },
      { id: "eref-K2041-segqc", reportId: "sreport-K-2041-rad-quant-01", sourceType: "segmentation_qc", sourceId: "segqc-K-2041-01", includedByRole: "radiologist", includedAt: "2026-06-12T08:28:00Z", visibility: "radiologist", limitations: [], evidenceSummary: "Segmentation QC accepted for quantitative review.", patientVisible: false },
    ],
    sections: [
      { id: "sec-K2041-quant", reportId: "sreport-K-2041-rad-quant-01", sectionType: "quantitative_biomarker_summary", title: "Quantitative biomarker summary", status: "reviewed", content: "Radiologist-reviewed volumetry, corticometry, and AD-relevant quantitative evidence are referenced as structured evidence.", structuredItems: [{ id: "item-K2041-quant-source", label: "Source outputs", value: "Volumetry, corticometry, AD summary", sourceEvidenceReferenceId: "eref-K2041-vol-output", patientVisible: false }], evidenceReferenceIds: ["eref-K2041-vol-output", "eref-K2041-hoc-metric", "eref-K2041-segqc"], authorRole: "radiologist", reviewerRole: "radiologist", createdAt: "2026-06-12T08:28:00Z", updatedAt: "2026-06-12T08:34:00Z", limitations: ["Raw metrics are not patient-visible."], patientVisible: false, requiredForCompletion: true },
      { id: "sec-K2041-quant-limit", reportId: "sreport-K-2041-rad-quant-01", sectionType: "limitations", title: "Limitations", status: "reviewed", content: "Quantitative outputs are decision-support evidence and require clinical context.", structuredItems: [], evidenceReferenceIds: [], authorRole: "radiologist", reviewerRole: "radiologist", createdAt: "2026-06-12T08:28:00Z", updatedAt: "2026-06-12T08:34:00Z", limitations: [], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Structured report object references evidence by ID; PDF is only a future rendering."],
    version: "structured report v0.1",
    patientVisible: false,
    researchEligible: true,
    pdfRenderable: true,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2041-rad-visual-01",
    caseId: "K-2041",
    reportType: "radiologist_reviewed_quantitative_summary",
    status: "reviewed",
    createdAt: "2026-06-12T08:35:00Z",
    updatedAt: "2026-06-12T08:40:00Z",
    createdByRole: "radiologist",
    primaryOwnerRole: "radiologist",
    intendedAudience: "internal_clinical",
    sourceMriStudyIds: ["mri-K-2041-T0"],
    sourceBiomarkerOutputIds: [],
    sourceStructuredVisualAssessmentIds: ["sva-K-2041-01"],
    sourceRadiologistHandoffIds: ["handoff-K-2041-01"],
    evidenceReferences: [
      { id: "eref-K2041-sva", reportId: "sreport-K-2041-rad-visual-01", sourceType: "structured_visual_assessment", sourceId: "sva-K-2041-01", includedByRole: "radiologist", includedAt: "2026-06-12T08:35:00Z", visibility: "physician", limitations: ["Visual assessment is imaging evidence, not final diagnosis."], evidenceSummary: "Completed structured dementia MRI visual assessment referenced by ID.", patientVisible: false },
      { id: "eref-K2041-mta-score", reportId: "sreport-K-2041-rad-visual-01", sourceType: "visual_rating_score", sourceId: "score-K2041-mta-l", includedByRole: "radiologist", includedAt: "2026-06-12T08:35:00Z", visibility: "physician", limitations: ["Raw visual scores are not patient-visible."], evidenceSummary: "MTA score referenced for physician-facing imaging context.", patientVisible: false },
      { id: "eref-K2041-handoff", reportId: "sreport-K-2041-rad-visual-01", sourceType: "radiologist_imaging_handoff", sourceId: "handoff-K-2041-01", includedByRole: "radiologist", includedAt: "2026-06-12T08:35:00Z", visibility: "physician", limitations: ["Handoff is not final clinical interpretation."], evidenceSummary: "Radiologist imaging handoff referenced for physician synthesis.", patientVisible: false },
    ],
    sections: [
      { id: "sec-K2041-protocol-quality", reportId: "sreport-K-2041-rad-visual-01", sectionType: "mri_protocol_and_quality", title: "MRI protocol and quality", status: "reviewed", content: "Protocol completeness and image quality were reviewed as structured evidence.", structuredItems: [{ id: "item-K2041-quality", label: "Quality", value: "Suitable for visual assessment", patientVisible: false }], evidenceReferenceIds: ["eref-K2041-sva"], authorRole: "radiologist", reviewerRole: "radiologist", createdAt: "2026-06-12T08:35:00Z", updatedAt: "2026-06-12T08:40:00Z", limitations: [], patientVisible: false, requiredForCompletion: true },
      { id: "sec-K2041-visual", reportId: "sreport-K-2041-rad-visual-01", sectionType: "structured_visual_assessment", title: "Structured visual assessment", status: "reviewed", content: "Visual rating scales and structured imaging findings are referenced for clinical synthesis.", structuredItems: [{ id: "item-K2041-scores", label: "Visual scores", value: "MTA, Fazekas, Koedam, GCA referenced internally", sourceEvidenceReferenceId: "eref-K2041-mta-score", patientVisible: false }], evidenceReferenceIds: ["eref-K2041-sva", "eref-K2041-mta-score"], authorRole: "radiologist", reviewerRole: "radiologist", createdAt: "2026-06-12T08:35:00Z", updatedAt: "2026-06-12T08:40:00Z", limitations: ["Raw visual scores are not patient-safe content."], patientVisible: false, requiredForCompletion: true },
      { id: "sec-K2041-handoff", reportId: "sreport-K-2041-rad-visual-01", sectionType: "radiologist_handoff", title: "Radiologist handoff", status: "reviewed", content: "Imaging evidence is ready for physician clinical synthesis.", structuredItems: [], evidenceReferenceIds: ["eref-K2041-handoff"], authorRole: "radiologist", reviewerRole: "radiologist", createdAt: "2026-06-12T08:35:00Z", updatedAt: "2026-06-12T08:40:00Z", limitations: ["Handoff is not patient-facing."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Structured visual scores remain separate from AI biomarkers."],
    version: "structured report v0.1",
    patientVisible: false,
    researchEligible: true,
    pdfRenderable: false,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2041-phys-evidence-01",
    caseId: "K-2041",
    reportType: "physician_facing_evidence_summary",
    status: "physician_synthesis_draft",
    createdAt: "2026-06-12T09:00:00Z",
    updatedAt: "2026-06-12T09:00:00Z",
    createdByRole: "physician_neurologist",
    primaryOwnerRole: "physician_neurologist",
    intendedAudience: "physician",
    sourceMriStudyIds: ["mri-K-2041-T0"],
    sourceBiomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    sourceStructuredVisualAssessmentIds: ["sva-K-2041-01"],
    sourceRadiologistHandoffIds: ["handoff-K-2041-01"],
    evidenceReferences: [
      { id: "eref-K2041-phys-bio-view", reportId: "sreport-K-2041-phys-evidence-01", sourceType: "clinical_biomarker_view", sourceId: "clinical-biomarker-view-K-2041", includedByRole: "physician_neurologist", includedAt: "2026-06-12T09:00:00Z", visibility: "physician", limitations: ["Only reviewed/suitable biomarker evidence is included."], evidenceSummary: "Physician-facing reviewed biomarker view referenced.", patientVisible: false },
      { id: "eref-K2041-phys-visual", reportId: "sreport-K-2041-phys-evidence-01", sourceType: "structured_visual_assessment", sourceId: "sva-K-2041-01", includedByRole: "physician_neurologist", includedAt: "2026-06-12T09:00:00Z", visibility: "physician", limitations: ["Visual assessment does not determine diagnosis."], evidenceSummary: "Radiologist-reviewed structured visual assessment referenced.", patientVisible: false },
    ],
    sections: [
      { id: "sec-K2041-clin-placeholder", reportId: "sreport-K-2041-phys-evidence-01", sectionType: "clinical_context_placeholder", title: "Clinical context placeholder", status: "draft", content: "Clinical context will be authored by the physician in a later workflow.", structuredItems: [], evidenceReferenceIds: [], authorRole: "physician_neurologist", createdAt: "2026-06-12T09:00:00Z", updatedAt: "2026-06-12T09:00:00Z", limitations: ["No clinical diagnosis is generated."], patientVisible: false, requiredForCompletion: true },
      { id: "sec-K2041-phys-evidence", reportId: "sreport-K-2041-phys-evidence-01", sectionType: "quantitative_biomarker_summary", title: "Reviewed imaging evidence", status: "draft", content: "Reviewed biomarker and structured visual evidence are referenced for physician synthesis.", structuredItems: [], evidenceReferenceIds: ["eref-K2041-phys-bio-view", "eref-K2041-phys-visual"], authorRole: "physician_neurologist", createdAt: "2026-06-12T09:00:00Z", updatedAt: "2026-06-12T09:00:00Z", limitations: ["Evidence is decision support only."], patientVisible: false, requiredForCompletion: true },
      { id: "sec-K2041-phys-synth", reportId: "sreport-K-2041-phys-evidence-01", sectionType: "physician_synthesis_placeholder", title: "Physician synthesis placeholder", status: "not_started", content: "Physician-owned synthesis is not implemented in PR5.", structuredItems: [], evidenceReferenceIds: [], authorRole: "physician_neurologist", createdAt: "2026-06-12T09:00:00Z", updatedAt: "2026-06-12T09:00:00Z", limitations: ["Full report lifecycle is out of scope."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["This is a structured draft object, not a final clinical report."],
    version: "physician evidence draft v0.1",
    patientVisible: false,
    researchEligible: false,
    pdfRenderable: false,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2041-patient-safe-draft-01",
    caseId: "K-2041",
    reportType: "patient_safe_summary",
    status: "patient_safe_summary_draft",
    createdAt: "2026-06-12T09:05:00Z",
    updatedAt: "2026-06-12T09:05:00Z",
    createdByRole: "physician_neurologist",
    primaryOwnerRole: "physician_neurologist",
    intendedAudience: "patient_safe",
    sourceMriStudyIds: [],
    sourceBiomarkerOutputIds: [],
    sourceStructuredVisualAssessmentIds: [],
    sourceRadiologistHandoffIds: [],
    evidenceReferences: [],
    sections: [
      { id: "sec-K2041-patient-safe", reportId: "sreport-K-2041-patient-safe-draft-01", sectionType: "patient_safe_summary_placeholder", title: "Patient-safe summary placeholder", status: "draft", content: "Your specialist-reviewed summary is being prepared.", structuredItems: [], evidenceReferenceIds: [], authorRole: "physician_neurologist", createdAt: "2026-06-12T09:05:00Z", updatedAt: "2026-06-12T09:05:00Z", limitations: ["Draft only; not published to patient portal."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Patient-safe summary requires later approval and publication gate."],
    version: "patient-safe draft v0.1",
    patientVisible: false,
    researchEligible: false,
    pdfRenderable: true,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2042-rad-quant-draft-01",
    caseId: "K-2042",
    reportType: "radiologist_reviewed_quantitative_summary",
    status: "draft",
    createdAt: "2026-06-13T11:00:00Z",
    updatedAt: "2026-06-13T11:00:00Z",
    createdByRole: "radiologist",
    primaryOwnerRole: "radiologist",
    intendedAudience: "radiologist",
    sourceMriStudyIds: ["mri-K-2042-T0"],
    sourceBiomarkerOutputIds: ["bio-K-2042-vol-01"],
    sourceStructuredVisualAssessmentIds: ["sva-K-2042-01"],
    sourceRadiologistHandoffIds: [],
    evidenceReferences: [
      { id: "eref-K2042-vol-output", reportId: "sreport-K-2042-rad-quant-draft-01", sourceType: "biomarker_output", sourceId: "bio-K-2042-vol-01", sourceVersion: "output 01", includedByRole: "radiologist", includedAt: "2026-06-13T11:00:00Z", visibility: "radiologist", limitations: ["Pending radiologist review."], evidenceSummary: "Unreviewed quantitative output referenced for radiologist draft only.", patientVisible: false },
    ],
    sections: [
      { id: "sec-K2042-quant-draft", reportId: "sreport-K-2042-rad-quant-draft-01", sectionType: "quantitative_biomarker_summary", title: "Quantitative draft", status: "draft", content: "Quantitative output is pending radiologist review.", structuredItems: [], evidenceReferenceIds: ["eref-K2042-vol-output"], authorRole: "radiologist", createdAt: "2026-06-13T11:00:00Z", updatedAt: "2026-06-13T11:00:00Z", limitations: ["Not physician-facing until review completes."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Draft only; not suitable for physician or patient views."],
    version: "structured report draft v0.1",
    patientVisible: false,
    researchEligible: false,
    pdfRenderable: false,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2043-phys-evidence-01",
    caseId: "K-2043",
    reportType: "physician_facing_evidence_summary",
    status: "reviewed",
    createdAt: "2026-05-27T13:40:00Z",
    updatedAt: "2026-05-27T13:45:00Z",
    createdByRole: "physician_neurologist",
    primaryOwnerRole: "physician_neurologist",
    intendedAudience: "physician",
    sourceMriStudyIds: ["mri-K-2043-T1"],
    sourceBiomarkerOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    sourceStructuredVisualAssessmentIds: ["sva-K-2043-01"],
    sourceRadiologistHandoffIds: ["handoff-K-2043-01"],
    evidenceReferences: [
      { id: "eref-K2043-long-output", reportId: "sreport-K-2043-phys-evidence-01", sourceType: "biomarker_output", sourceId: "bio-K-2043-long-01", sourceVersion: "longitudinal output 01", includedByRole: "physician_neurologist", includedAt: "2026-05-27T13:40:00Z", visibility: "physician", limitations: ["Relative interval comparison only."], evidenceSummary: "Reviewed longitudinal biomarker output referenced.", patientVisible: false },
      { id: "eref-K2043-visual", reportId: "sreport-K-2043-phys-evidence-01", sourceType: "structured_visual_assessment", sourceId: "sva-K-2043-01", includedByRole: "physician_neurologist", includedAt: "2026-05-27T13:40:00Z", visibility: "physician", limitations: ["Visual follow-up context only."], evidenceSummary: "Structured visual follow-up assessment referenced.", patientVisible: false },
    ],
    sections: [
      { id: "sec-K2043-phys-evidence", reportId: "sreport-K-2043-phys-evidence-01", sectionType: "quantitative_biomarker_summary", title: "Follow-up evidence summary", status: "reviewed", content: "Reviewed follow-up quantitative and visual evidence are referenced for physician context.", structuredItems: [], evidenceReferenceIds: ["eref-K2043-long-output", "eref-K2043-visual"], authorRole: "physician_neurologist", reviewerRole: "physician_neurologist", createdAt: "2026-05-27T13:40:00Z", updatedAt: "2026-05-27T13:45:00Z", limitations: ["No autonomous progression diagnosis."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Physician-facing evidence summary is not patient-safe output."],
    version: "physician evidence v1.0",
    patientVisible: false,
    researchEligible: false,
    pdfRenderable: false,
    sourceOfTruth: "structured_data",
  },
  {
    id: "sreport-K-2043-patient-safe-draft-01",
    caseId: "K-2043",
    reportType: "patient_safe_summary",
    status: "patient_safe_summary_draft",
    createdAt: "2026-05-27T14:00:00Z",
    updatedAt: "2026-05-27T14:00:00Z",
    createdByRole: "physician_neurologist",
    primaryOwnerRole: "physician_neurologist",
    intendedAudience: "patient_safe",
    sourceMriStudyIds: [],
    sourceBiomarkerOutputIds: [],
    sourceStructuredVisualAssessmentIds: [],
    sourceRadiologistHandoffIds: [],
    evidenceReferences: [],
    sections: [
      { id: "sec-K2043-patient-safe", reportId: "sreport-K-2043-patient-safe-draft-01", sectionType: "patient_safe_summary_placeholder", title: "Patient-safe follow-up summary placeholder", status: "draft", content: "Your specialist-reviewed follow-up summary is available after clinic approval.", structuredItems: [], evidenceReferenceIds: [], authorRole: "physician_neurologist", createdAt: "2026-05-27T14:00:00Z", updatedAt: "2026-05-27T14:00:00Z", limitations: ["Publication workflow is out of scope for PR5."], patientVisible: false, requiredForCompletion: true },
    ],
    limitations: ["Draft placeholder; patient portal publication is not implemented here."],
    version: "patient-safe draft v0.1",
    patientVisible: false,
    researchEligible: false,
    pdfRenderable: true,
    sourceOfTruth: "structured_data",
  },
];

export const physicianClinicalSyntheses: PhysicianClinicalSynthesis[] = [
  {
    id: "phys-synth-K-2041-01",
    caseId: "K-2041",
    status: "draft",
    createdAt: "2026-06-12T09:15:00Z",
    updatedAt: "2026-06-12T09:20:00Z",
    createdByRole: "physician_neurologist",
    physicianReviewerRole: "physician_neurologist",
    sourceReportIds: ["sreport-K-2041-rad-quant-01", "sreport-K-2041-rad-visual-01", "sreport-K-2041-phys-evidence-01"],
    sourceRadiologistHandoffIds: ["handoff-K-2041-01"],
    sourceStructuredVisualAssessmentIds: ["sva-K-2041-01"],
    sourceBiomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    sourceEvidenceReferenceIds: ["eref-K2041-phys-bio-view", "eref-K2041-phys-visual"],
    clinicalContextSummary: "Memory concerns and cognitive context are available for physician-owned synthesis.",
    imagingEvidenceSummary: "Radiologist handoff and structured visual MRI review are available as imaging evidence.",
    quantitativeEvidenceSummary: "Reviewed quantitative evidence is available; raw AI output is excluded from synthesis wording.",
    structuredVisualEvidenceSummary: "Structured visual assessment is reviewed imaging evidence and does not determine diagnosis.",
    limitations: ["Draft clinical synthesis only; no final approval or publication has occurred."],
    clinicalInterpretationDraft: "Physician interpretation draft pending completion in clinical context.",
    differentialConsiderations: ["Requires physician-authored differential if clinically appropriate."],
    recommendationsDraft: ["No treatment recommendation is generated by Kio."],
    followUpConsiderations: ["Follow-up timing remains physician decision."],
    requiresAdditionalClinicalData: false,
    openQuestions: [],
    patientSafeSummaryDraftId: "ps-summary-K-2041-01",
    suitableForFinalApproval: false,
    patientVisible: false,
    researchEligible: false,
  },
  {
    id: "phys-synth-K-2043-01",
    caseId: "K-2043",
    status: "ready_for_review",
    createdAt: "2026-05-27T13:50:00Z",
    updatedAt: "2026-05-27T14:05:00Z",
    createdByRole: "physician_neurologist",
    physicianReviewerRole: "physician_neurologist",
    sourceReportIds: ["sreport-K-2043-phys-evidence-01"],
    sourceRadiologistHandoffIds: ["handoff-K-2043-01"],
    sourceStructuredVisualAssessmentIds: ["sva-K-2043-01"],
    sourceBiomarkerOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    sourceEvidenceReferenceIds: ["eref-K2043-long-output", "eref-K2043-visual"],
    clinicalContextSummary: "Follow-up clinical context is available for physician synthesis.",
    imagingEvidenceSummary: "Radiologist-reviewed follow-up imaging evidence is available.",
    quantitativeEvidenceSummary: "Reviewed longitudinal quantitative evidence is available as decision support.",
    structuredVisualEvidenceSummary: "Structured visual follow-up review is available with comparability limitation.",
    limitations: ["Follow-up evidence is context only; Kio does not generate progression diagnosis."],
    clinicalInterpretationDraft: "Physician-owned follow-up synthesis draft.",
    differentialConsiderations: [],
    recommendationsDraft: ["Continue care discussion outside Kio; no treatment recommendation generated."],
    followUpConsiderations: ["Next review point can be coordinated if physician confirms."],
    requiresAdditionalClinicalData: false,
    openQuestions: [],
    patientSafeSummaryDraftId: "ps-summary-K-2043-01",
    suitableForFinalApproval: false,
    patientVisible: false,
    researchEligible: false,
  },
];

export const physicianEvidenceReviews: PhysicianEvidenceReview[] = [
  {
    id: "phys-evrev-K-2041-01",
    caseId: "K-2041",
    physicianSynthesisId: "phys-synth-K-2041-01",
    reviewedAt: "2026-06-12T09:12:00Z",
    reviewedByRole: "physician_neurologist",
    reviewedReportIds: ["sreport-K-2041-rad-quant-01", "sreport-K-2041-rad-visual-01", "sreport-K-2041-phys-evidence-01"],
    reviewedBiomarkerOutputIds: ["bio-K-2041-vol-01", "bio-K-2041-cort-01", "bio-K-2041-ad-01"],
    reviewedStructuredVisualAssessmentIds: ["sva-K-2041-01"],
    reviewedRadiologistHandoffIds: ["handoff-K-2041-01"],
    evidenceAdequacyStatus: "adequate_with_limitations",
    missingInformation: [],
    limitations: ["Clinical interpretation must be physician-authored; quantitative evidence is decision support only."],
    reviewNotes: "Reviewed radiologist handoff, visual assessment, and reviewed biomarker evidence.",
    readyForSynthesis: true,
  },
  {
    id: "phys-evrev-K-2043-01",
    caseId: "K-2043",
    physicianSynthesisId: "phys-synth-K-2043-01",
    reviewedAt: "2026-05-27T13:48:00Z",
    reviewedByRole: "physician_neurologist",
    reviewedReportIds: ["sreport-K-2043-phys-evidence-01"],
    reviewedBiomarkerOutputIds: ["bio-K-2043-vol-01", "bio-K-2043-long-01"],
    reviewedStructuredVisualAssessmentIds: ["sva-K-2043-01"],
    reviewedRadiologistHandoffIds: ["handoff-K-2043-01"],
    evidenceAdequacyStatus: "adequate_with_limitations",
    missingInformation: [],
    limitations: ["Longitudinal comparison is relative imaging evidence, not autonomous progression diagnosis."],
    reviewNotes: "Follow-up evidence reviewed for physician-owned synthesis.",
    readyForSynthesis: true,
  },
];

export const patientSafeSummaryDrafts: PatientSafeSummaryDraft[] = [
  {
    id: "ps-summary-K-2041-01",
    caseId: "K-2041",
    physicianSynthesisId: "phys-synth-K-2041-01",
    status: "draft",
    createdAt: "2026-06-12T09:25:00Z",
    updatedAt: "2026-06-12T09:25:00Z",
    createdByRole: "physician_neurologist",
    audience: "patient_and_caregiver",
    plainLanguageSummary: "Your specialist is reviewing your MRI information and clinical context.",
    whatWasReviewed: "Specialist-reviewed MRI information and the information you provided are being considered together.",
    whatThisMeans: "This draft does not provide a diagnosis. Your specialist will explain the result in clinical context.",
    limitationsInPlainLanguage: ["Some technical details are used only by the care team."],
    recommendedNextSteps: ["Discuss the final reviewed summary with your specialist team."],
    followUpInstructions: [],
    caregiverNotes: ["Caregiver-facing wording requires the same publication review."],
    excludedUnsafeContent: [
      { id: "exclude-K2041-raw-ai", excludedContentType: "raw_ai_output", reason: "Raw AI output is not patient-safe.", sourceId: "bio-K-2041-vol-01", sourceType: "biomarker_output" },
      { id: "exclude-K2041-percentile", excludedContentType: "percentile_table", reason: "Percentile tables require clinical explanation and are not included in draft patient wording.", sourceId: "met-K2041-hoc", sourceType: "biomarker_metric" },
      { id: "exclude-K2041-segmentation", excludedContentType: "segmentation_map", reason: "Segmentation maps are internal imaging review evidence.", sourceId: "segqc-K-2041-01", sourceType: "segmentation_qc" },
      { id: "exclude-K2041-visual", excludedContentType: "raw_visual_score", reason: "Raw visual rating scores are not patient-facing content.", sourceId: "score-K2041-mta-l", sourceType: "visual_rating_score" },
      { id: "exclude-K2041-internal", excludedContentType: "internal_note", reason: "Internal specialist notes are not patient-safe draft content.", sourceId: "phys-synth-K-2041-01", sourceType: "clinical_synthesis" },
    ],
    sourceEvidenceReferenceIds: [],
    readyForPublicationReview: false,
    patientVisible: false,
  },
  {
    id: "ps-summary-K-2043-01",
    caseId: "K-2043",
    physicianSynthesisId: "phys-synth-K-2043-01",
    status: "ready_for_publication_review",
    createdAt: "2026-05-27T14:10:00Z",
    updatedAt: "2026-05-27T14:18:00Z",
    createdByRole: "physician_neurologist",
    audience: "patient_and_caregiver",
    plainLanguageSummary: "Your specialist-reviewed follow-up summary has been prepared for review.",
    whatWasReviewed: "Your follow-up MRI information and clinical context were reviewed by the specialist team.",
    whatThisMeans: "This summary is intended to be discussed with your clinic or specialist team.",
    limitationsInPlainLanguage: ["Technical measurements and internal review notes are not shown here."],
    recommendedNextSteps: ["Review the summary with your clinic if you have questions."],
    followUpInstructions: ["The next follow-up point can be coordinated by the clinic."],
    caregiverNotes: ["Caregiver access depends on the clinic's permission settings."],
    excludedUnsafeContent: [
      { id: "exclude-K2043-raw-ai", excludedContentType: "raw_ai_output", reason: "Raw AI output is not patient-safe.", sourceId: "bio-K-2043-long-01", sourceType: "biomarker_output" },
      { id: "exclude-K2043-percentile", excludedContentType: "percentile_table", reason: "Raw quantitative tables are excluded from patient wording.", sourceId: "met-K2043-hip-change", sourceType: "biomarker_metric" },
      { id: "exclude-K2043-visual", excludedContentType: "raw_visual_score", reason: "Raw visual rating scores remain imaging evidence.", sourceId: "score-K2043-mta-b", sourceType: "visual_rating_score" },
      { id: "exclude-K2043-research", excludedContentType: "research_metadata", reason: "Research metadata is separate from patient communication.", sourceId: "R-1204", sourceType: "research_metadata" },
    ],
    sourceEvidenceReferenceIds: [],
    readyForPublicationReview: true,
    patientVisible: false,
  },
];

export const publicationApprovals: PublicationApproval[] = [
  {
    id: "pub-approval-K-2041-01",
    caseId: "K-2041",
    status: "requested",
    createdAt: "2026-06-12T09:35:00Z",
    updatedAt: "2026-06-12T09:35:00Z",
    requestedByRole: "physician_neurologist",
    sourcePhysicianSynthesisId: "phys-synth-K-2041-01",
    sourcePatientSafeSummaryDraftId: "ps-summary-K-2041-01",
    sourceStructuredReportIds: ["sreport-K-2041-patient-safe-draft-01"],
    approvalNotes: "Publication review requested; not approved or patient-visible.",
    patientVisible: false,
    auditEventIds: ["audit-pub-K2041-requested"],
  },
  {
    id: "pub-approval-K-2043-01",
    caseId: "K-2043",
    status: "approved",
    createdAt: "2026-05-27T14:20:00Z",
    updatedAt: "2026-05-27T14:28:00Z",
    requestedByRole: "physician_neurologist",
    approvedByRole: "physician_neurologist",
    approvedAt: "2026-05-27T14:28:00Z",
    sourcePhysicianSynthesisId: "phys-synth-K-2043-01",
    sourcePatientSafeSummaryDraftId: "ps-summary-K-2043-01",
    sourceStructuredReportIds: ["sreport-K-2043-patient-safe-draft-01", "sreport-K-2043-phys-evidence-01"],
    approvalNotes: "Physician approved patient-safe wording for portal release. Raw evidence remains excluded.",
    patientVisible: false,
    auditEventIds: ["audit-pub-K2043-approved"],
  },
  {
    id: "pub-approval-K-2042-01",
    caseId: "K-2042",
    status: "returned_for_revision",
    createdAt: "2026-06-13T11:15:00Z",
    updatedAt: "2026-06-13T11:35:00Z",
    requestedByRole: "physician_neurologist",
    rejectedByRole: "physician_neurologist",
    rejectedAt: "2026-06-13T11:35:00Z",
    sourcePhysicianSynthesisId: "not-started",
    sourcePatientSafeSummaryDraftId: "not-created",
    sourceStructuredReportIds: ["sreport-K-2042-rad-quant-draft-01"],
    rejectionReason: "Patient-safe summary is not ready because imaging review is incomplete.",
    patientVisible: false,
    auditEventIds: ["audit-pub-K2042-returned"],
  },
];

export const patientReleasePackages: PatientReleasePackage[] = [
  {
    id: "release-K-2041-draft-01",
    caseId: "K-2041",
    status: "pending_publication_approval",
    createdAt: "2026-06-12T09:36:00Z",
    updatedAt: "2026-06-12T09:36:00Z",
    publicationApprovalId: "pub-approval-K-2041-01",
    sourcePatientSafeSummaryDraftId: "ps-summary-K-2041-01",
    sourcePhysicianSynthesisId: "phys-synth-K-2041-01",
    sourceStructuredReportIds: ["sreport-K-2041-patient-safe-draft-01"],
    releaseTitle: "Specialist-reviewed summary",
    plainLanguageSummary: "Your specialist is reviewing your MRI information and clinical context.",
    whatWasReviewed: "Specialist-reviewed MRI information and the information you provided are being considered together.",
    whatThisMeans: "This draft does not provide a diagnosis. Your specialist will explain the result in clinical context.",
    limitationsInPlainLanguage: ["Some technical details are used only by the care team."],
    recommendedNextSteps: ["Discuss the final reviewed summary with your specialist team."],
    followUpInstructions: [],
    caregiverNotes: ["Caregiver-facing wording requires the same publication review."],
    excludedUnsafeContent: patientSafeSummaryDrafts[0].excludedUnsafeContent,
    attachments: [
      { id: "att-K2041-summary", type: "patient_safe_summary", label: "Patient-safe summary draft", sourceId: "ps-summary-K-2041-01", sourceType: "patient_safe_summary_draft", patientVisible: false, safeDescription: "Draft summary metadata only; not visible until approval and release." },
      { id: "att-K2041-pdf-placeholder", type: "rendered_pdf_placeholder", label: "Future PDF rendering placeholder", sourceId: "sreport-K-2041-patient-safe-draft-01", sourceType: "rendered_pdf_placeholder", patientVisible: false, safeDescription: "PDF rendering is a future export format, not the source of truth." },
    ],
    patientVisible: false,
    caregiverVisible: false,
    auditEventIds: ["audit-release-K2041-draft"],
  },
  {
    id: "release-K-2043-portal-01",
    caseId: "K-2043",
    status: "released_to_patient_portal",
    createdAt: "2026-05-27T14:30:00Z",
    updatedAt: "2026-05-28T09:00:00Z",
    publicationApprovalId: "pub-approval-K-2043-01",
    sourcePatientSafeSummaryDraftId: "ps-summary-K-2043-01",
    sourcePhysicianSynthesisId: "phys-synth-K-2043-01",
    sourceStructuredReportIds: ["sreport-K-2043-patient-safe-draft-01", "sreport-K-2043-phys-evidence-01"],
    releaseTitle: "Specialist-reviewed follow-up summary",
    plainLanguageSummary: "Your specialist-reviewed follow-up summary is available. Please review it with your clinic or specialist team if you have questions about your care.",
    whatWasReviewed: "Your follow-up MRI information and clinical context were reviewed by the specialist team.",
    whatThisMeans: "This summary is intended to support a conversation with your clinic. It is not an AI diagnosis or treatment recommendation.",
    limitationsInPlainLanguage: ["Technical measurements, raw scores, internal review notes, and research metadata are not shown in the portal."],
    recommendedNextSteps: ["Review the summary with your clinic if you have questions."],
    followUpInstructions: ["Your next follow-up review point is scheduled for December 2026."],
    caregiverNotes: ["Caregiver access depends on clinic permission settings."],
    excludedUnsafeContent: patientSafeSummaryDrafts[1].excludedUnsafeContent,
    attachments: [
      { id: "att-K2043-summary", type: "patient_safe_summary", label: "Patient-safe follow-up summary", sourceId: "ps-summary-K-2043-01", sourceType: "patient_safe_summary_draft", patientVisible: true, safeDescription: "Approved plain-language summary released to the portal." },
      { id: "att-K2043-followup", type: "follow_up_note", label: "Follow-up reminder", sourceId: "K-2043-follow-up", sourceType: "follow_up_coordination", patientVisible: true, safeDescription: "Clinic-managed follow-up coordination note." },
      { id: "att-K2043-pdf-placeholder", type: "rendered_pdf_placeholder", label: "PDF placeholder", sourceId: "sreport-K-2043-patient-safe-draft-01", sourceType: "rendered_pdf_placeholder", patientVisible: false, safeDescription: "Future rendering metadata only; no PDF is generated in this PR." },
    ],
    patientVisible: true,
    caregiverVisible: false,
    releasedAt: "2026-05-28T09:00:00Z",
    releasedByRole: "operations_coordinator",
    auditEventIds: ["audit-release-K2043-portal"],
  },
];

export const patientReleaseSafetyChecks: PatientReleaseSafetyCheck[] = [
  {
    id: "release-safety-K-2041-01",
    caseId: "K-2041",
    releasePackageId: "release-K-2041-draft-01",
    checkedAt: "2026-06-12T09:37:00Z",
    checkedByRole: "physician_neurologist",
    status: "pending",
    blockedReasons: ["Publication approval is not complete."],
    excludedUnsafeContent: patientSafeSummaryDrafts[0].excludedUnsafeContent,
    safeForPatientRelease: false,
    notes: "Draft package exists but is not patient-visible.",
  },
  {
    id: "release-safety-K-2043-01",
    caseId: "K-2043",
    releasePackageId: "release-K-2043-portal-01",
    checkedAt: "2026-05-28T08:45:00Z",
    checkedByRole: "physician_neurologist",
    status: "passed",
    blockedReasons: [],
    excludedUnsafeContent: patientSafeSummaryDrafts[1].excludedUnsafeContent,
    safeForPatientRelease: true,
    notes: "Release package excludes raw AI output, percentile tables, segmentation maps, raw visual scores, internal notes, and research metadata.",
  },
];

export const roleDefinitions = {
  operations: {
    label: "Operations / Case Management",
    shortLabel: "Operations",
    purpose: "Manage case flow, blockers, assignments, release administration, and follow-up coordination.",
    permission: "Workflow and administrative status. No clinical interpretation.",
    accent: "teal",
  },
  radiologist: {
    label: "Radiologist Review",
    shortLabel: "Radiologist",
    purpose: "Review MRI quality and AI-generated quantitative imaging evidence before physician interpretation.",
    permission: "Imaging and AI review. No patient release or final clinical interpretation.",
    accent: "blue",
  },
  physician: {
    label: "Neurologist / Physician Review",
    shortLabel: "Physician",
    purpose: "Interpret radiologist-reviewed imaging evidence in clinical context and approve patient-safe output.",
    permission: "Clinical context, reviewed imaging, interpretation, and release approval.",
    accent: "indigo",
  },
  patient: {
    label: "Patient Portal",
    shortLabel: "Patient",
    purpose: "Complete required actions, understand safe status, and access physician-approved released output.",
    permission: "Own safe status, forms, uploads, consent, and released output only.",
    accent: "sage",
  },
  caregiver: {
    label: "Caregiver Portal",
    shortLabel: "Caregiver",
    purpose: "Support your family member: track safe status, help complete requested actions, and access brain-health guidance.",
    permission: "Patient-safe status, requested actions, education, and released summary only.",
    accent: "slate",
  },
  research: {
    label: "Research Workspace",
    shortLabel: "Research",
    purpose: "Build anonymized cohorts, inspect quantitative metrics, and prepare governed research exports.",
    permission: "Consented, anonymized, research-appropriate data only.",
    accent: "slate",
  },
} as const;
