import type { AuditEvent } from "./domain/audit";
import type { CaseBlocker, CaseState } from "./domain/caseState";
import type { OwnerRoleLabel } from "./domain/caseStateSelectors";

export type RoleId = "operations" | "radiologist" | "physician" | "patient" | "caregiver" | "research";

export type TimelineEvent = {
  label: string;
  detail: string;
  date: string;
  tone?: "default" | "good" | "attention";
  patientSafe?: boolean;
};

export type Finding = {
  region: string;
  volume: string;
  percentile: number;
  comparison: string;
  indication?: string;
};

export type CreateCaseFormValues = {
  patientName: string;
  age: number;
  sex: "Female" | "Male";
  referralSource: string;
  assignedRadiologist: string;
  assignedNeurologist: string;
  mriSource: "PACS" | "Patient upload link" | "Not available yet";
  intakeStatus: "Not requested" | "Requested" | "Completed";
  consentStatus: "Not requested" | "Requested" | "Completed";
  caregiverName?: string;
  caregiverContact?: string;
  priorImagingAvailable: "Yes" | "No" | "Unknown";
  operationsNote?: string;
};

export type KioCase = {
  id: string;
  state: CaseState;
  stateEnteredAt?: string;
  blockers?: CaseBlocker[];
  auditEvents?: AuditEvent[];
  mriStudyIds?: string[];
  aiProcessingJobIds?: string[];
  biomarkerOutputIds?: string[];
  quantitativeReportIds?: string[];
  protocolCompletenessAssessmentIds?: string[];
  imageQualityAssessmentIds?: string[];
  structuredVisualAssessmentIds?: string[];
  radiologistHandoffIds?: string[];
  structuredReportIds?: string[];
  physicianSynthesisIds?: string[];
  physicianEvidenceReviewIds?: string[];
  patientSafeSummaryDraftIds?: string[];
  anonymizedId: string;
  patientName: string;
  age: number;
  ageGroup: string;
  sex: "Female" | "Male";
  scanDate: string;
  caseStatus: string;
  mriStatus: string;
  intakeStatus: string;
  aiStatus: string;
  radiologistStatus: string;
  neurologistStatus: string;
  reportStatus: string;
  patientSummaryStatus: string;
  pdfReleaseStatus: string;
  releaseStatus: string;
  followUpStatus: string;
  nextAction: string;
  currentOwnerRole: OwnerRoleLabel;
  blocker?: string;
  referralSource?: string;
  mriSource?: string;
  caregiverName?: string;
  caregiverContact?: string;
  priorImagingAvailable?: "Yes" | "No" | "Unknown";
  operationsNote?: string;
  assignedRadiologist: string;
  assignedNeurologist: string;
  imageQuality: string;
  memoryComplaint: string;
  cognitiveHistory: string;
  cognitiveScore: string;
  caregiverObservation: string;
  keyFindings: string[];
  findings: Finding[];
  timeline: TimelineEvent[];
  outputVersion: string;
  reportVersion: string;
  amendmentStatus: string;
  researchEligible: boolean;
  researchConsent: string;
  consentScope: string;
  anonymizationStatus: string;
  anonymizationMethod: string;
  researchTimepoint: string;
  datasetVersion: string;
  exportVersion: string;
  withdrawalStatus: string;
  longitudinal: boolean;
  patientSafeStatus: string;
  patientNextAction: string;
  patientApprovedSummary?: string;
  patientFormProgress: number;
  consentStatus: string;
  radiologistComment: string;
  physicianNote: string;
};
